CREATE DATABASE MEU_CURSO
COLLATE Latin1_General_100_CI_AS_SC_UTF8;

CREATE TABLE PESSOAS (

	NOME VARCHAR (30) NOT NULL,
	NASCIMENTO DATE,
	SEXO CHAR (1) CHECK (SEXO IN ('M','F')),
	PESO DECIMAL (5,2),
	ALTURA DECIMAL (3,2),
	NACIONALIDADE VARCHAR (20) DEFAULT 'BRASIL'
);

ALTER TABLE PESSOAS 
ADD ID INT IDENTITY(1,1) PRIMARY KEY;


