CREATE TABLE [TABELA DE CLIENTES](

[CPF] [CHAR] (11),
[NOME] [VARCHAR] (50),
[RUA] [VARCHAR] (50),
[COMPLEMENTO] [VARCHAR] (50),
[BAIRRO] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE], 
[IDADE] [SMALLINT], 
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY], 
[VOLUME MINIMO] [FLOAT],
[PRIMEIRA COMPRA] [BIT]

);

CREATE TABLE [TABELA DE PRODUTO](

[CODIGO DO PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
[NOME DO PRODUTO] [VARCHAR] (50), 
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO DA LISTA] [SMALLMONEY]

);

SELECT * FROM [TABELA DE PRODUTO];

UPDATE [TABELA DE PRODUTO]
SET [EMBALAGEM] =
    CASE
        -- PET (1L, 1.5L, 2L)
        WHEN [TAMANHO] IN ('1 Litro', '1,5 Litros', '2 Litros') THEN 'PET'
        
        -- Garrafa (700ml, 600ml)
        WHEN [TAMANHO] IN ('700 ml', '600 ml') THEN 'Garrafa'
        
        -- Caçulinha (500ml)
        WHEN [TAMANHO] = '500 ml' THEN 'Caçulinha'
        
        -- Lata (350ml)
        WHEN [TAMANHO] = '350 ml' THEN 'Lata'
        
        -- Default: Se não cair em nenhuma regra, mantém o valor original (NULL)
        ELSE [EMBALAGEM] 
    END;


ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTE
PRIMARY KEY CLUSTERED ([CPF]);

CREATE TABLE [TABELA DE VENDEDORES](

[MATRICULA] VARCHAR (5) NOT NULL PRIMARY KEY,
[NOME] VARCHAR (100),
[PERCENTUAL DE COMISSAO] FLOAT
);

CREATE TABLE VENDAS (
    ID_VENDA INT PRIMARY KEY,
    CPF VARCHAR(11),
    CODIGO_DO_PRODUTO INT,
    MATRICULA INT,
    DATA_VENDA DATE,
    QUANTIDADE INT
);

INSERT INTO VENDAS VALUES

(1, '12345678901', 101, 1001, '2025-08-01', 3),
(2, '98765432100', 102, 1002, '2025-08-05', 1),
(3, '12345678901', 103, 1001, '2025-08-10', 5),
(4, '55566677788', 101, 1003, '2025-08-12', 2),
(5, '98765432100', 104, 1002, '2025-08-15', 4),
(6, '44433322211', 105, 1003, '2025-08-18', 6),
(7, '55566677788', 102, 1001, '2025-08-20', 2),
(8, '99988877766', 101, 1002, '2025-08-21', 7),
(9, '12345678901', 104, 1003, '2025-08-22', 1),
(10, '44433322211', 103, 1001, '2025-08-25', 3);


INSERT INTO [TABELA DE PRODUTO] VALUES (

'1040107',
'light - 350 ml - melancia',
'lata',
'350 ml',
'Melancia',
4.56

);

INSERT INTO [TABELA DE PRODUTO] VALUES 
('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01),
('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31),
('1004327', 'Videira do Campo - 1,5 Litros - Melancia', 'PET', '1,5 Litros', 'Melancia', 19.51),
('1088126', 'Linha Citros - 1 Litro Limão', 'PET', '1 Litro', 'Limão', 7.00);

INSERT INTO [TABELA DE CLIENTES] VALUES
('00384393431', 'João da Silva', 'Rua Projetada A', 'Numero 233', 'Copacabana', 'RJ', '20000000',
'1965-03-21', 57, 'M', 200000, 3000.30, 1),
('00384393555', 'Maria Clara', 'Rua Projetada A', 'Numero 233', 'Copacabana',
'RJ', '20000000', '1975-03-21', 47, 'F', 200000, 3000.30, 0);

INSERT INTO [TABELA DE VENDEDORES] VALUES
('00236', 'CLAUDIA MORAIS', 0.08),
('00237', 'MARCELA FERREIRA', 0.09),
('00238', 'MARCIO ALMEIDA', 0.08);

INSERT INTO [TABELA DE PRODUTO] 
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [PRECO DA LISTA], [SABOR])
VALUES
('5449310', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml', 2.45, 'Limão'),
('1078680', 'Frescor de Verão - 350 ml - Manga', 'Lata', '350 ml', 3.18, 'Manga');

SELECT * FROM [TABELA DE PRODUTO];

SELECT [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTO];

SELECT [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTO]
ORDER BY [TAMANHO];

SELECT [NOME] AS [NOME DO CLIENTE], [CPF] FROM [TABELA DE CLIENTES];

SELECT [SABOR] FROM [TABELA DE PRODUTO];

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTO];

SELECT [NOME] AS [NOME DO CLIENTE], [PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTO]
WHERE [PRECO DA LISTA] = 7.00;

SELECT * FROM [TABELA DE PRODUTO]
WHERE [PRECO DA LISTA] >= 7.00;

INSERT INTO [TABELA DE CLIENTES] VALUES
('12345678900', 'Pedro Almeida', 'Rua das Laranjeiras', 'Numero 45', 'Botafogo', 'RJ', '22250000', '1980-06-15', 44, 'M', 250000, 1500.75, 0),
('98765432100', 'Larissa Gomes', 'Avenida Brasil', 'Numero 890', 'Centro', 'RJ', '20040000', '1992-11-03', 29, 'F', 180000, 200.00, 0),
('45678912300', 'Roberto Souza', 'Rua do Catete', 'Numero 310', 'Glória', 'RJ', '22220000', '1970-02-28', 55, 'M', 300000, 5000.00, 1),
('32165498700', 'Camila Duarte', 'Travessa do Comércio', 'Numero 12', 'Centro', 'RJ', '20010000', '1988-08-09', 36, 'F', 220000, 750.50, 0),
('15975346800', 'Fernando Reis', 'Rua São Clemente', 'Numero 99', 'Botafogo', 'RJ', '22260000', '1960-12-01', 63, 'M', 280000, 3200.20, 1);

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] >= '1985-01-01';

SELECT * FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) > '1985';

SELECT [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) > '1985';

SELECT [NOME], [BAIRRO] FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Centro' OR [BAIRRO] = 'Botafogo';

SELECT [NOME], [BAIRRO], [ESTADO], [PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' AND [PRIMEIRA COMPRA] = '1';

SELECT [NOME], [BAIRRO] FROM [TABELA DE CLIENTES]
WHERE NOT [BAIRRO] = 'Copacabana';

SELECT [NOME], [BAIRRO] FROM [TABELA DE CLIENTES]
WHERE NOT (BAIRRO ='Centro' OR BAIRRO = 'Botafogo');

SELECT * FROM [TABELA DE PRODUTO] WHERE SABOR IN ('Uva','Laranja');

SELECT [NOME DO PRODUTO] FROM [TABELA DE PRODUTO] WHERE SABOR IN ('Laranja', 'Melancia') AND [PRECO DA LISTA] >= 5.00;

SELECT * FROM [TABELA DE PRODUTO] WHERE SABOR IN ('Melancia','Uva') AND ([PRECO DA LISTA] BETWEEN 5.00 AND 7.00);



SELECT SABOR, SUM ([PRECO DA LISTA]) AS [PRECO DA LISTA] FROM [TABELA DE PRODUTO] GROUP BY SABOR;
SELECT TAMANHO, SUM ([PRECO DA LISTA]) AS [PRECO DA LISTA] FROM [TABELA DE PRODUTO] GROUP BY TAMANHO;

SELECT TOP 3 * FROM [TABELA DE CLIENTES] WHERE SEXO = 'M';
SELECT TOP 5 [NOME DO PRODUTO], [PRECO DA LISTA] FROM [TABELA DE PRODUTO] WHERE [PRECO DA LISTA] >= 10.00;

INSERT INTO [TABELA DE PRODUTO] (
    [CODIGO DO PRODUTO], 
    [NOME DO PRODUTO], 
    [EMBALAGEM], 
    [TAMANHO], 
    [SABOR], 
    [PRECO DA LISTA]
)
VALUES 
(1090011, 'Refresco do Campo - 1 Litro - Uva',         'PET',     '1 Litro',    'Uva',      5.75),
(1090012, 'Sabor Puro - 2 Litros - Manga',             'PET',     '2 Litros',   'Manga',    17.89),
(1090013, 'Verão Leve - 500 ml - Limão',               'Garrafa', '500 ml',     'Limão',    4.20),
(1090014, 'Fresh+ - 350 ml - Laranja',                 'Lata',    '350 ml',     'Laranja',  2.85),
(1090015, 'Citrus Mix - 1,5 Litros - Melancia',        'PET',     '1,5 Litros', 'Melancia', 15.60),
(1090016, 'Natural+ - 600 ml - Manga',                 'Garrafa', '600 ml',     'Manga',    5.45),
(1090017, 'Vida Leve - 2 Litros - Limão',              'PET',     '2 Litros',   'Limão',    12.95),
(1090018, 'Suco Puro - 700 ml - Laranja',              'Garrafa', '700 ml',     'Laranja',  7.90),
(1090019, 'Tropicool - 350 ml - Uva',                  'Lata',    '350 ml',     'Uva',      3.65),
(1090020, 'Vital Drink - 1 Litro - Manga',             'PET',     '1 Litro',    'Manga',    6.80);

INSERT INTO [TABELA DE VENDEDORES] (
[MATRICULA],[NOME],[PERCENTUAL DE COMISSAO]
)
VALUES
('00239', 'ALISSON MENDES', 0.10),
('00240', 'REBECA FERNANDES', 0.06),
('00241', 'HUMBERTO COSTA', 0.08),
('00242', 'GABRIELA REGO', 0.09),
('00243', 'ANTONIO CARLOS', 0.05);

INSERT INTO [TABELA DE CLIENTES] (CPF, NOME, ESTADO, [LIMITE DE CREDITO])
VALUES
('12343678901', 'Ana Silva', 'SP', 5000),
('98762432100', 'Carlos Souza', 'RJ', 3000),
('55565677788', 'Mariana Oliveira', 'MG', 4000),
('44437322211', 'João Santos', 'PR', 2000),
('99989877766', 'Fernanda Lima', 'BA', 3500);

UPDATE [TABELA DE CLIENTES] 
SET 
    RUA = COALESCE(RUA, 'Endereço Não Cadastrado'),
    COMPLEMENTO = COALESCE(COMPLEMENTO, 'Informação Não Fornecida'),
    BAIRRO = COALESCE(BAIRRO, 
        CASE ESTADO 
            WHEN 'RJ' THEN 'Centro'
            WHEN 'SP' THEN 'Centro'
            WHEN 'MG' THEN 'Savassi'
            WHEN 'PR' THEN 'Centro Cívico'
            WHEN 'BA' THEN 'Comércio'
            ELSE 'Centro'
        END),
    CEP = COALESCE(CEP,
        CASE ESTADO 
            WHEN 'SP' THEN '01000000'
            WHEN 'PR' THEN '80000000' 
            WHEN 'MG' THEN '30000000'
            WHEN 'RJ' THEN '20000000'
            WHEN 'BA' THEN '40000000'
            ELSE '00000000'
        END),
    [DATA DE NASCIMENTO] = COALESCE([DATA DE NASCIMENTO], '1980-01-01'),
    IDADE = COALESCE(IDADE, DATEDIFF(YEAR, COALESCE([DATA DE NASCIMENTO], '1980-01-01'), GETDATE())),
    SEXO = COALESCE(SEXO, 
        CASE 
            WHEN ESTADO IN ('SP', 'MG') THEN 'F'
            ELSE 'M'
        END),
    [VOLUME MINIMO] = COALESCE([VOLUME MINIMO], 1000.00),
    [PRIMEIRA COMPRA] = COALESCE([PRIMEIRA COMPRA], 0)
WHERE RUA IS NULL 
   OR COMPLEMENTO IS NULL 
   OR BAIRRO IS NULL 
   OR CEP IS NULL 
   OR [DATA DE NASCIMENTO] IS NULL 
   OR IDADE IS NULL 
   OR SEXO IS NULL 
   OR [VOLUME MINIMO] IS NULL 
   OR [PRIMEIRA COMPRA] IS NULL;


SELECT * FROM [TABELA DE CLIENTES] ORDER BY [VOLUME MINIMO];
SELECT * FROM [TABELA DE CLIENTES] ORDER BY [VOLUME MINIMO] DESC;
SELECT * FROM [TABELA DE CLIENTES] ORDER BY [DATA DE NASCIMENTO];
SELECT * FROM [TABELA DE CLIENTES] WHERE SEXO = 'F' ORDER BY [LIMITE DE CREDITO] DESC;

SELECT EMBALAGEM, AVG ([PRECO DA LISTA]) AS PREÇO FROM [TABELA DE PRODUTO] 
GROUP BY EMBALAGEM ORDER BY PREÇO DESC;

SELECT TAMANHO, AVG ([PRECO DA LISTA]) AS PREÇO FROM [TABELA DE PRODUTO] 
GROUP BY TAMANHO ORDER BY PREÇO DESC;


SELECT * FROM [TABELA DE CLIENTES];
SELECT * FROM [TABELA DE PRODUTO];
SELECT * FROM [TABELA DE VENDEDORES];

SELECT BAIRRO, COUNT (*) AS CLIENTES FROM [TABELA DE CLIENTES] GROUP BY BAIRRO ORDER BY CLIENTES DESC;
SELECT SABOR, COUNT (*) AS PRODUTO FROM [TABELA DE PRODUTO] GROUP BY SABOR ORDER BY PRODUTO DESC;
SELECT EMBALAGEM, COUNT (*) AS PRODUTO FROM [TABELA DE PRODUTO] WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM;
SELECT BAIRRO, COUNT (*) AS SEXO FROM [TABELA DE CLIENTES] WHERE SEXO = 'M' GROUP BY BAIRRO;

SELECT IDADE, [LIMITE DE CREDITO] AS CREDITO FROM [TABELA DE CLIENTES]
WHERE [LIMITE DE CREDITO] >= 3000 ORDER BY CREDITO DESC;

SELECT IDADE, AVG ([LIMITE DE CREDITO]) AS CREDITO  FROM [TABELA DE CLIENTES]
GROUP BY IDADE HAVING AVG ([LIMITE DE CREDITO]) >= 3000 ORDER BY CREDITO DESC; 

SELECT BAIRRO, SUM ([LIMITE DE CREDITO]) AS CREDITO FROM [TABELA DE CLIENTES]
GROUP BY BAIRRO HAVING SUM ([LIMITE DE CREDITO]) >= 350000.00;

SELECT SABOR, SUM ([PRECO DA LISTA]) AS VALOR FROM [TABELA DE PRODUTO]
GROUP BY SABOR HAVING SUM ([PRECO DA LISTA]) >= 30 ORDER BY VALOR DESC;

SELECT SEXO, AVG ([LIMITE DE CREDITO]) AS CREDITO FROM [TABELA DE CLIENTES]
GROUP BY SEXO ORDER BY CREDITO DESC; 

SELECT SEXO, [LIMITE DE CREDITO] AS CREDITO FROM [TABELA DE CLIENTES]
WHERE [LIMITE DE CREDITO] >= 10000;

SELECT NOME, [LIMITE DE CREDITO],
(CASE WHEN [LIMITE DE CREDITO] >= 250000.00 THEN 'CLIENTE VIP'
	WHEN [LIMITE DE CREDITO] >= 200000.00 AND [LIMITE DE CREDITO] < 250000.00 THEN 'CLIENTE INTERMEDIÁRIO'
	ELSE 'CLIENTE COMUM' END) AS TIER
FROM [TABELA DE CLIENTES] ORDER BY [LIMITE DE CREDITO] DESC;

SELECT [NOME DO PRODUTO], [PRECO DA LISTA],
(CASE WHEN [PRECO DA LISTA] >= 15 THEN 'CARO'
	WHEN [PRECO DA LISTA] >= 7 AND [PRECO DA LISTA] < 15 THEN 'REGULAR'
	ELSE 'BARATO' END) AS VALOR
FROM [TABELA DE PRODUTO] ORDER BY [PRECO DA LISTA] DESC;

SELECT * FROM [TABELA DE VENDEDORES] ORDER BY [PERCENTUAL DE COMISSAO] DESC;

SELECT NOME, [PERCENTUAL DE COMISSAO],
(CASE WHEN [PERCENTUAL DE COMISSAO] >= 0.09 THEN 'VENDEDOR PREMIUM'
	WHEN [PERCENTUAL DE COMISSAO] >= 0.07 AND [PERCENTUAL DE COMISSAO] < 0.09  THEN 'VENDEDOR PRO'
	ELSE 'VENDEDOR JUNIOR' END) AS CLASSIFICAÇÃO
FROM [TABELA DE VENDEDORES] ORDER BY [PERCENTUAL DE COMISSAO] DESC;

SELECT * FROM VENDAS;

SELECT
    [TABELA DE CLIENTES].NOME AS [Nome Cliente],
    [TABELA DE VENDEDORES].NOME AS [Nome Vendedor],
    [TABELA DE PRODUTO].[NOME DO PRODUTO] AS Produto,
    VENDAS.QUANTIDADE,
    VENDAS.DATA_VENDA
FROM VENDAS
LEFT JOIN [TABELA DE CLIENTES] ON VENDAS.CPF = [TABELA DE CLIENTES].CPF
LEFT JOIN [TABELA DE PRODUTO] ON VENDAS.CODIGO_DO_PRODUTO = [TABELA DE PRODUTO].[CODIGO DO PRODUTO]
LEFT JOIN [TABELA DE VENDEDORES] ON VENDAS.MATRICULA = [TABELA DE VENDEDORES].MATRICULA;

SELECT 
	[TABELA DE CLIENTES].NOME AS [NOME CLIENTE],
	[TABELA DE VENDEDORES].NOME AS [NOME VENDEDOR],
	[TABELA DE PRODUTO].[NOME DO PRODUTO] AS PRODUTO,
	VENDAS.QUANTIDADE,
	VENDAS.DATA_VENDA
FROM VENDAS
RIGHT JOIN [TABELA DE CLIENTES] ON VENDAS.CPF = [TABELA DE CLIENTES].CPF
RIGHT JOIN [TABELA DE PRODUTO] ON VENDAS.CODIGO_DO_PRODUTO = [TABELA DE PRODUTO].[CODIGO DO PRODUTO]
RIGHT JOIN [TABELA DE VENDEDORES] ON VENDAS.MATRICULA = [TABELA DE VENDEDORES].MATRICULA;

SELECT
    [TABELA DE CLIENTES].NOME AS [Nome Cliente],
    [TABELA DE VENDEDORES].NOME AS [Nome Vendedor],
    [TABELA DE PRODUTO].[NOME DO PRODUTO] AS Produto,
    VENDAS.QUANTIDADE,
    VENDAS.DATA_VENDA
FROM VENDAS
INNER JOIN [TABELA DE CLIENTES] ON VENDAS.CPF = [TABELA DE CLIENTES].CPF
INNER JOIN [TABELA DE PRODUTO] ON VENDAS.CODIGO_DO_PRODUTO = [TABELA DE PRODUTO].[CODIGO DO PRODUTO]
INNER JOIN [TABELA DE VENDEDORES] ON VENDAS.MATRICULA = [TABELA DE VENDEDORES].MATRICULA;

SELECT
	[TABELA DE CLIENTES].NOME AS [NOME DE CLIENTE],
	[TABELA DE VENDEDORES].NOME AS [NOME DE VENDEDOR],
	[TABELA DE PRODUTO].[NOME DO PRODUTO] AS PRODUTO,
	VENDAS.QUANTIDADE,
	VENDAS.DATA_VENDA
FROM VENDAS
FULL JOIN [TABELA DE CLIENTES] ON VENDAS.CPF = [TABELA DE CLIENTES].CPF
FULL JOIN [TABELA DE PRODUTO] ON VENDAS.CODIGO_DO_PRODUTO = [TABELA DE PRODUTO].[CODIGO DO PRODUTO]
FULL JOIN [TABELA DE VENDEDORES] ON VENDAS.MATRICULA = [TABELA DE VENDEDORES].MATRICULA;
















