SELECT * FROM NOTAS_FISCAIS

SELECT	
    TABELA_DE_VENDEDORES.NOME,
	NOTAS_FISCAIS.MATRICULA
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_VENDEDORES ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
INNER JOIN ITENS_NOTAS_FISCAIS ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO;
  
SELECT
    NOTAS_FISCAIS.NUMERO,
    NOTAS_FISCAIS.DATA_VENDA,
    NOTAS_FISCAIS.MATRICULA,
    TABELA_DE_CLIENTES.CPF,
    TABELA_DE_CLIENTES.NOME,
    TABELA_DE_CLIENTES.BAIRRO,
    TABELA_DE_CLIENTES.CIDADE,
    TABELA_DE_CLIENTES.ESTADO,
    TABELA_DE_CLIENTES.DATA_DE_NASCIMENTO
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_CLIENTES ON NOTAS_FISCAIS.CPF = TABELA_DE_CLIENTES.CPF


SELECT
    NOTAS_FISCAIS.NUMERO,
    NOTAS_FISCAIS.DATA_VENDA,
    NOTAS_FISCAIS.MATRICULA,
    TABELA_DE_CLIENTES.CPF,
    TABELA_DE_CLIENTES.NOME,
    TABELA_DE_CLIENTES.BAIRRO,
    TABELA_DE_CLIENTES.CIDADE,
    TABELA_DE_CLIENTES.ESTADO,
    TABELA_DE_CLIENTES.DATA_DE_NASCIMENTO
FROM NOTAS_FISCAIS
FULL JOIN TABELA_DE_CLIENTES ON NOTAS_FISCAIS.CPF = TABELA_DE_CLIENTES.CPF;

SELECT 
	



	